/* ==================================================================
   DADOS DO CATALOGO, /ed/ia-automacao/

   Gerado a partir das 7 paginas de formacao (ed/formacoes/f1..f7).
   Cada curso guarda os MESMOS campos que o .course-card original usa,
   pra o .course-modal de /ed/formacoes/ funcionar sem adaptacao.

   Os Business Cases NAO vivem aqui: vem do objeto AREAS de
   /ed/business-cases/script.js, carregado junto nesta pagina.
   ================================================================== */

/* Formacoes na ordem em que os chips aparecem. A F6 vem primeiro por ser
   o produto de entrada desta pagina. */
var FORMACOES = [
    { id: 'f6', curto: 'IA e Automação', nome: 'Inteligência Artificial e Automação', carga: '~62h', cursos: 10,
      icone: '/ed/site-dependencias/site-media/formacoes/icones/Automação & IA.svg' },
    { id: 'f1', curto: 'Power BI Básico', nome: 'Power BI Básico ao Intermediário', carga: '~38h', cursos: 8,
      icone: '/ed/site-dependencias/site-media/formacoes/icones/Power BI Básico.svg' },
    { id: 'f2', curto: 'Power BI Avançado', nome: 'Power BI Intermediário ao Avançado', carga: '~103h', cursos: 9,
      icone: '/ed/site-dependencias/site-media/formacoes/icones/Power BI Intermediário.svg' },
    { id: 'f3', curto: 'Microsoft Fabric', nome: 'Microsoft Fabric', carga: '~53h', cursos: 3,
      icone: '/ed/site-dependencias/site-media/formacoes/icones/Microsoft Fabric.svg' },
    { id: 'f4', curto: 'Banco de Dados e SQL', nome: 'Banco de Dados e SQL', carga: '~57h', cursos: 4,
      icone: '/ed/site-dependencias/site-media/formacoes/icones/Banco de Dados & SQL.svg' },
    { id: 'f5', curto: 'Python e Data Science', nome: 'Python e Data Science', carga: '~58h', cursos: 7,
      icone: '/ed/site-dependencias/site-media/formacoes/icones/Python & Data Science.svg' },
    { id: 'f7', curto: 'Carreira e Negócios', nome: 'Carreira e Negócios', carga: '~31h', cursos: 6,
      icone: '/ed/site-dependencias/site-media/formacoes/icones/Carreira & Negócios.svg' }
];

/* Os 47 cursos. `f` amarra o curso a formacao (chave `id` acima). */
var CURSOS = [
    { f: 'f6', titulo: 'Imersão Bê-a-bá da IA',
      dur: '13h', aulas: '56', prof: 'César Germano',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/Imersão Bê-a-bá da IA.webp',
      desc: 'Bê-a-bá da IA é uma imersão prática para quem quer aprender a usar Inteligência Artificial de forma simples e aplicada no dia a dia. Você vai conhecer as principais ferramentas do mercado, criar automações, construir páginas em minutos e sair com clareza sobre como aplicar IA no seu trabalho ou negócio.' },
    { f: 'f6', titulo: 'Desvendando a Inteligência Artificial e o ChatGPT',
      dur: '1h', aulas: '15', prof: 'César Germano',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/Desvendando a Inteligência Artificial e o ChatGPT.webp',
      desc: 'Aprenda os fundamentos da IA e descubra como usar o ChatGPT no dia a dia. Em apenas 1 hora, você vai aprender a criar prompts eficazes, explorar geração de conteúdo e dados, e aplicar IA com mais confiança e produtividade.' },
    { f: 'f6', titulo: 'Projetos Práticos com Inteligência Artificial',
      dur: '1h', aulas: '8', prof: 'César Germano',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/Projetos Práticos com Inteligência Artificial.webp',
      desc: 'Aplique IA em desafios reais com projetos guiados. Em 1 hora, aprenda a resolver problemas de startups, conteúdo digital, produtividade e análise de dados. Uma abordagem prática para transformar teoria em ação.' },
    { f: 'f6', titulo: 'Crie Apps e Sites com IA usando Lovable',
      dur: '2h', aulas: '8', prof: 'César Germano',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/Crie Apps e Sites com IA usando Lovable.webp',
      desc: 'Aprenda a transformar ideias em sites e plataformas web funcionais usando Lovable, a ferramenta de vibe-coding que escreve o código por você. Em 5 aulas práticas, você sai do zero, sem precisar saber programar, até publicar seu próprio projeto online, incluindo páginas de portfólio, landing pages e até uma plataforma completa com banco de dados via Supabase. É o caminho mais rápido pra quem quer parar de depender de programador, validar uma ideia rápido ou criar produtos digitais usando IA como motor de execução.' },
    { f: 'f6', titulo: 'N8N, Automação Inteligente de Tarefas e Processos',
      dur: '6h', aulas: '29', prof: 'César Germano',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/N8N, Automação Inteligente de Tarefas e Processos.webp',
      desc: 'Domine o N8N e crie automações eficientes. Em cerca de 6 horas, aprenda a construir fluxos visuais, integrar APIs, tratar dados e otimizar processos com controle e escalabilidade em diferentes áreas.' },
    { f: 'f6', titulo: 'Python, LLMs e Agentes de IA',
      dur: '2h', aulas: '13', prof: 'César Germano',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/Python, LLMs e Agentes de IA.webp',
      desc: 'Aprenda a usar Python com modelos de linguagem para criar aplicações inteligentes. Em 4 horas, conecte APIs, trabalhe com embeddings e LangChain, e desenvolva agentes com lógica, memória e autonomia.' },
    { f: 'f6', titulo: 'Power Automate Essencial',
      dur: '14h', aulas: '40', prof: 'Anderson Rocha',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/Power Automate Essencial.webp',
      desc: 'Domine o Power Automate para automatizar processos de negócios. Este curso abrange os conceitos essenciais e técnicas práticas para criar fluxos de trabalho eficientes, aumentando a produtividade e a automação de tarefas.' },
    { f: 'f6', titulo: 'Power Apps Essencial',
      dur: '13h', aulas: '69', prof: 'Daniel Petrin',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/Power Apps Essencial.webp',
      desc: 'Aprenda a criar aplicativos com Power Apps. Este curso aborda os fundamentos e práticas para construir aplicativos personalizados, otimizando processos e melhorando a eficiência em suas atividades, com foco no desenvolvimento de soluções.' },
    { f: 'f6', titulo: 'Power Apps, Aplicativo de Checklist',
      dur: '3h', aulas: '22', prof: 'Daniel Petrin',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/Power Apps, Aplicativo de Checklist.webp',
      desc: 'Crie um aplicativo de checklist prático com Power Apps. Este curso guia você através do processo de desenvolvimento de um aplicativo funcional, aplicando conceitos essenciais de design e funcionalidade para otimizar fluxos de trabalho.' },
    { f: 'f6', titulo: 'Power Apps, Aplicativo de Gestão de Documentos',
      dur: '7h', aulas: '40', prof: 'Daniel Petrin',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f6/Power Apps, Aplicativo de Gestão de Documentos.webp',
      desc: 'Crie aplicativos de gestão de documentos eficazes com o Power Apps. Este curso prático orienta você na construção de aplicativos personalizados para simplificar o gerenciamento de documentos e dados, melhorando a eficiência organizacional.' },
    { f: 'f1', titulo: 'Fundamentos de Análise de Dados',
      dur: '4h', aulas: '33', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f1/Fundamentos de Análise de Dados.webp',
      desc: 'Aprenda os aspectos essenciais da análise de dados, começando com uma introdução ao tema e avançando para conceitos mais complexos. Este curso é perfeito para quem está começando na área e deseja construir uma base sólida em análise de dados, preparando-o para desafios futuros.' },
    { f: 'f1', titulo: 'Power Query Essencial 2.0',
      dur: '4h', aulas: '16', prof: 'Esdras Santana',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f1/Power Query Essencial 2.0.webp',
      desc: 'Este curso é uma introdução essencial ao Power Query. Aprenda os princípios fundamentais para importar, transformar e combinar dados de forma eficiente, capacitando você a realizar análises avançadas de dados com facilidade.' },
    { f: 'f1', titulo: 'Modelagem de Dados Essencial 2.0',
      dur: '3h', aulas: '12', prof: 'Esdras Santana',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f1/Modelagem de Dados Essencial 2.0.webp',
      desc: 'Construa uma base sólida em modelagem de dados com este curso essencial. Aprenda os princípios fundamentais para estruturar dados de forma eficiente e eficaz, garantindo uma base sólida para suas atividades de análise de dados.' },
    { f: 'f1', titulo: 'Linguagem DAX Essencial 2.0',
      dur: '7h', aulas: '27', prof: 'Esdras Santana',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f1/Linguagem DAX Essencial 2.0.webp',
      desc: 'Explore os conceitos essenciais da linguagem DAX, desde os fundamentos até aplicações práticas. Ideal para quem deseja construir uma base sólida em DAX, o curso capacita você a realizar análises avançadas de dados com facilidade, utilizando essa linguagem poderosa.' },
    { f: 'f1', titulo: 'Storytelling e Visualização de Dados Essencial 2.0',
      dur: '8h', aulas: '56', prof: 'Esdras Santana',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f1/Storytelling e Visualização de Dados Essencial 2.0.webp',
      desc: 'Aprenda os princípios fundamentais para criar visualizações claras e impactantes, capacitando você a comunicar insights valiosos por meio de gráficos e representações visuais eficazes.' },
    { f: 'f1', titulo: 'Design de Dashboards com o Figma 2.0',
      dur: '5h', aulas: '24', prof: 'Sayuri Valente',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f1/Design de Dashboards com o Figma 2.0.webp',
      desc: 'Domine a arte de criar dashboards visualmente impactantes e eficazes usando o Figma. Este curso aborda desde os fundamentos do design de dashboards até técnicas avançadas para apresentar dados de forma clara e atraente, combinando estética e funcionalidade.' },
    { f: 'f1', titulo: 'Power BI Serviço Essencial 2.0',
      dur: '3h', aulas: '13', prof: 'Esdras Santana',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f1/Power BI Serviço Essencial 2.0.webp',
      desc: 'Aprenda a utilizar o Power BI Service para compartilhar e colaborar em relatórios. Este curso essencial cobre os recursos-chave do serviço para maximizar o impacto de suas análises, facilitando a colaboração com sua equipe.' },
    { f: 'f1', titulo: 'Projeto Final, Case de Controladoria com DRE',
      dur: '4h', aulas: '32', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f1/Projeto Final, Case de Controladoria com DRE.webp',
      desc: 'Trabalhe com um departamento de controladoria para desenvolver um dashboard que exiba a Demonstração de Resultados (DRE) de forma clara e eficaz. Mostre sua aptidão em comunicação de informações financeiras.' },
    { f: 'f2', titulo: 'Power Query Avançado',
      dur: '7h', aulas: '49', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f2/Power Query Avançado.webp',
      desc: 'Aprofunde-se no Power Query com técnicas avançadas de transformação de dados. Este curso abrange desde a limpeza de dados complexos até a combinação de fontes diversas, permitindo que você domine a arte da manipulação de dados eficiente.' },
    { f: 'f2', titulo: 'APIs e Linguagem M Avançado',
      dur: '13h', aulas: '59', prof: 'Paulo Sawaya',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f2/APIs e Linguagem M Avançado.webp',
      desc: 'Aprofunde-se nas técnicas de integração e transformação de dados com APIs e a Linguagem M no Power BI. Ideal para quem busca habilidades avançadas em acessar, tratar e enriquecer dados de diversas fontes, potencializando a criação de relatórios e análises de negócios.' },
    { f: 'f2', titulo: 'Modelagem de Dados Avançado',
      dur: '7h', aulas: '21', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f2/Modelagem de Dados Avançado.webp',
      desc: 'Avance suas habilidades em modelagem de dados com técnicas e conceitos avançados. Este curso é ideal para quem já tem conhecimento básico e deseja aprofundar suas competências, preparando-se para desafios analíticos mais complexos.' },
    { f: 'f2', titulo: 'Trabalhando com Grandes Bases Corporativas',
      dur: '4h', aulas: '25', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f2/Trabalhando com Grandes Bases Corporativas.webp',
      desc: 'Domine a arte de lidar com grandes conjuntos de dados e projetos corporativos, desenvolvendo estratégias e técnicas para enfrentar desafios analíticos complexos com sucesso.' },
    { f: 'f2', titulo: 'Linguagem DAX Avançado',
      dur: '11h', aulas: '79', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f2/Linguagem DAX Avançado.webp',
      desc: 'Aprofunde-se em aspectos complexos da linguagem DAX. Este curso é projetado para expandir suas habilidades e conhecimento em DAX, abordando tópicos avançados e técnicas sofisticadas para análise de dados avançada.' },
    { f: 'f2', titulo: 'Análises Avançadas com DAX',
      dur: '12h', aulas: '49', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f2/Análises Avançadas com DAX.webp',
      desc: 'Desenvolva habilidades de nível especialista em Business Intelligence e resolva projetos do mundo real com expressões avançadas de Análise de Dados (DAX). Este curso é uma jornada profunda no universo do DAX, oferecendo uma compreensão detalhada de técnicas e funções avançadas para manipulação e análise de dados complexos em Power BI.' },
    { f: 'f2', titulo: 'Business Analytics, Indicadores e KPIs',
      dur: '24h', aulas: '57', prof: 'Renan Giovaninni',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f2/Business Analytics, Indicadores e KPIs.webp',
      desc: 'Aprenda a construir e interpretar indicadores-chave de desempenho (KPIs) para análises de negócios eficazes. Este curso oferece conhecimento prático sobre como definir, medir e usar KPIs para impulsionar decisões estratégicas, ajudando a transformar dados em insights valiosos.' },
    { f: 'f2', titulo: 'Power BI Serviço Implantação 2.0',
      dur: '11h', aulas: '49', prof: 'Paulo Sawaya',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f2/Power BI Serviço Implantação 2.0.webp',
      desc: 'Aprofunde-se na administração, arquitetura e governança de dados no Power BI Service. Este curso aborda práticas recomendadas para garantir a integridade e eficiência dos seus dados, fortalecendo sua capacidade de gerenciamento.' },
    { f: 'f2', titulo: 'Projeto Final, Cases MR Bolos e HPN',
      dur: '14h', aulas: '70', prof: 'Felipe Martins',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f2/Projeto Final, Cases MR Bolos e HPN.webp',
      desc: 'Descubra como criar dashboards com um design premium e visualmente atraentes. Aprenda técnicas para combinar dados e design de forma eficaz, elevando a qualidade de suas apresentações de dados e impressionando seu público com visualizações impactantes.' },
    { f: 'f3', titulo: 'Fundamentos do Microsoft Fabric',
      dur: '12h', aulas: '33', prof: 'Diego Scalioni',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f3/Fundamentos do Microsoft Fabric.webp',
      desc: 'Descubra o Microsoft Fabric e sua abordagem unificada para análise e engenharia de dados, simplificando fluxos de trabalho e garantindo governança eficaz.' },
    { f: 'f3', titulo: 'Transformações com Microsoft Fabric',
      dur: '19h', aulas: '53', prof: 'Diego Scalioni',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f3/Transformações com Microsoft Fabric.webp',
      desc: 'Domine as ferramentas e técnicas para transformar e modelar dados dentro do Microsoft Fabric, criando pipelines eficientes para análises avançadas.' },
    { f: 'f3', titulo: 'Soluções Completas no Microsoft Fabric',
      dur: '22h', aulas: '42', prof: 'Diego Scalioni',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f3/Soluções Completas no Microsoft Fabric.webp',
      desc: 'Domine o Microsoft Fabric e suas capacidades para implementar soluções completas de dados, desde ingestão até análise avançada e governança.' },
    { f: 'f4', titulo: 'Raciocínio Lógico e Lógica de Programação',
      dur: '5h', aulas: '35', prof: 'Gustavo Ferreira',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f4/Raciocínio Lógico e Lógica de Programação.webp',
      desc: 'Refine seu raciocínio lógico e lógica de programação utilizando Portugol. Este curso é ideal para quem deseja aprofundar suas capacidades de solução de problemas e iniciar no mundo de programação, preparando-o para desafios analíticos mais complexos.' },
    { f: 'f4', titulo: 'Banco de Dados e Linguagem SQL',
      dur: '35h', aulas: '187', prof: 'Ítalo Mesquita',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f4/Banco de Dados e Linguagem SQL.webp',
      desc: 'Aprofunde-se no SQL Server com este curso avançado. Explore tópicos avançados de administração, consultas complexas e otimização de desempenho, adquirindo habilidades essenciais para lidar com bancos de dados robustos. Aprenda a criar um Data Warehouse com Linguagem SQL.' },
    { f: 'f4', titulo: 'Data Warehouse com Apache HOP',
      dur: '17h', aulas: '99', prof: 'Alex Pereira',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f4/Data Warehouse com Apache HOP.webp',
      desc: 'Aprenda a construir e gerenciar Data Warehouses eficientes utilizando o Apache HOP, uma das principais ferramentas de orquestração de dados no mercado.' },
    { f: 'f4', titulo: 'Minicurso de SQL',
      dur: '2h Bônus', aulas: '18', prof: 'Ítalo Mesquita',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f4/Minicurso de SQL.webp',
      desc: 'Este curso foi cuidadosamente elaborado para te guiar desde os primeiros passos na linguagem SQL até um domínio sólido e confiante. Com uma alta demanda no mercado de trabalho e aplicabilidade universal, aprender SQL abrirá portas em indústrias como tecnologia, saúde, varejo, e-commerce e muito mais.' },
    { f: 'f5', titulo: 'Python para Análise de Dados',
      dur: '9h', aulas: '60', prof: 'Leon Solón',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f5/Python para Análise de Dados.webp',
      desc: 'Aprenda Python do absoluto zero com uma das maiores referências na área. Prepare-se para aprimorar suas habilidades e ter um grande diferencial no mercado com esta poderosa linguagem para análise de dados. Aqui, exploraremos desde os conceitos básicos até os primeiros passos na manipulação de dados, fornecendo uma base sólida para futuras explorações na área de análise de dados.' },
    { f: 'f5', titulo: 'APIs com Python',
      dur: '3h', aulas: '7', prof: 'Anderson Rocha',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f5/APIs com Python.webp',
      desc: 'Descubra o poder do Python na conexão com APIs e transforme sua análise de dados! Neste curso vamos te ensinar a construir uma conexão API com Python de forma clara e prática, preparando você para explorar cenários reais de obtenção de dados em sistemas que não oferecem acesso direto ao banco de dados.' },
    { f: 'f5', titulo: 'Pandas para Análise Avançadas com Python',
      dur: '4h', aulas: '26', prof: 'Leon Solón',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f5/Pandas para Análise Avançadas com Python.webp',
      desc: 'Domine a biblioteca Pandas para análise de dados com Python. Este curso cobre desde as operações básicas até técnicas avançadas para manipulação de grandes conjuntos de dados, capacitando você a explorar insights valiosos.' },
    { f: 'f5', titulo: 'Estatística para Análise de Dados',
      dur: '9h', aulas: '49', prof: 'Yago Soares',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f5/Estatística para Análise de Dados.webp',
      desc: 'Explore o mundo da estatística aplicada à análise de dados. Este curso oferece uma base sólida em estatística, essencial para qualquer analista de dados, proporcionando as habilidades necessárias para interpretar e analisar dados com precisão.' },
    { f: 'f5', titulo: 'Introdução à Machine Learning',
      dur: '15h', aulas: '89', prof: 'Leon Solón',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f5/Introdução à Machine Learning.webp',
      desc: 'Tenha uma introdução abrangente ao mundo da Machine Learning. Este curso cobre os fundamentos e aplicações práticas da aprendizagem de máquina, sendo ideal para iniciantes que desejam entender os conceitos-chave dessa área fascinante.' },
    { f: 'f5', titulo: 'Databricks com Spark',
      dur: '8h', aulas: '61', prof: 'Fábio Marquez',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f5/Databricks com Spark.webp',
      desc: 'Mergulhe no mundo do processamento de big data e análises avançadas com Databricks e Spark. Aprenda a lidar com grandes volumes de dados, desenvolver pipelines de dados eficientes e realizar análises complexas, preparando-se para desafios de dados em grande escala.' },
    { f: 'f5', titulo: 'Projeto Final, Sistema de Recomendação',
      dur: '10h', aulas: '61', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f5/Projeto Final, Sistema de Recomendação.webp',
      desc: 'Ajude o gestor da Pinski Modas a superar o caos de suas planilhas! Neste desafio vamos criar acompanhamento de metas mensais, analisar desempenho da equipe de vendas e avaliar a performance dos produtos. Além disso, um grande desafio será a criação de um sistema de Recomendação de Produtos. Aprenda a organizar e interpretar dados, transformando informações caóticas em insights valiosos.' },
    { f: 'f7', titulo: 'Fundamentos de FP&A e Gestão Financeira',
      dur: '1h', aulas: '17', prof: 'Rafael Gross',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f7/Fundamentos de FP&A e Gestão Financeira.webp',
      desc: 'Aprenda a transformar números em estratégia e leve a tomada de decisão financeira para outro nível.' },
    { f: 'f7', titulo: 'Sales OPS',
      dur: 'Sales Ops', aulas: '', prof: 'Rafael Gross',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f7/Sales OPS.webp',
      desc: 'Você sai entendendo a engrenagem de vendas que sustenta empresa que cresce de forma previsível. Continuidade do contexto comercial.' },
    { f: 'f7', titulo: 'Produtividade e Gestão do Tempo',
      dur: '3h', aulas: '32', prof: 'Roberson Pinheiro',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f7/Produtividade e Gestão do Tempo.webp',
      desc: 'Melhore sua produtividade, gestão do tempo e performance com o curso Produtividade e Gestão do Tempo. Dividido em três blocos principais: performance, pensamento analítico e comunicação, este curso o tornará um profissional mais completo e estratégico. Aproveite cada aula e transforme sua carreira.' },
    { f: 'f7', titulo: 'LinkedIn Champion 2.0',
      dur: '3h', aulas: '24', prof: 'Sayuri Valente',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f7/LinkedIn Champion 2.0.webp',
      desc: 'Desenvolva sua presença profissional no LinkedIn. Aprenda estratégias e técnicas para destacar seu perfil e construir uma rede de contatos eficaz no mundo dos negócios e da análise de dados, aumentando suas oportunidades profissionais.' },
    { f: 'f7', titulo: 'Como Conseguir meu Primeiro Emprego',
      dur: '18h', aulas: '39', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f7/Como Conseguir meu Primeiro Emprego.webp',
      desc: 'Uma masterclass essencial para quem está buscando entrar no campo de dados. Receba orientações valiosas sobre como se posicionar e destacar no mercado de trabalho, aproveitando o poder do Power BI para impulsionar sua carreira.' },
    { f: 'f7', titulo: 'Como Prospectar Clientes',
      dur: '6h', aulas: '10', prof: 'Leonardo Karpinski',
      img: '/ed/site-dependencias/site-media/formacoes/aulas/f7/Como Prospectar Clientes.webp',
      desc: 'Uma mentoria focada em estratégias eficazes para prospecção de clientes. Ideal para profissionais que desejam expandir sua clientela e aumentar o alcance de seus serviços, com insights valiosos para o sucesso nos negócios.' }
];

